language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install httpretty==0.8.6"
  - "pip install mock"

script: "py.test ."
